name: Build Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish AemBinaryPatcher.csproj -c Release -o release --nologo
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AemulusBinaryPatcher
          path: /home/runner/work/AemBinaryPatcher/AemBinaryPatcher/release/